version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 17.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
    - 8.3.0
    - 8.5.0
  - dependency-name: next-pwa
    versions:
    - 5.2.9
    - 5.3.1
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.25.0
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.0
    - 5.11.10
    - 5.12.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
    - 3.4.0
    - 4.0.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 3.4.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.21.0
  - dependency-name: styled-components
    versions:
    - 5.1.1
    - 5.2.2
  - dependency-name: next
    versions:
    - 12.1.6
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.2.0
    - 6.0.0
    - 7.0.4
  - dependency-name: "@types/jest"
    versions:
    - 26.0.3
    - 26.0.20
    - 26.0.22
  - dependency-name: eslint-plugin-react
    versions:
    - 7.20.0
    - 7.23.0
    - 7.23.1
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 3.4.0
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.0
    - 5.1.8
    - 5.1.9
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
    - 17.0.27
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
    - 4.7.3
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.10.1
    - 7.12.17
    - 7.13.0
  - dependency-name: "@testing-library/react"
    versions:
    - 10.4.3
    - 11.2.3
    - 11.2.5